baseurl = "https://nosignal.github.io/"
languageCode = "en-us"
title = "Nosignal's Blog"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; 2017 Nosignal"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    # twitter = "Your Twitter username"
    github = "nosignal"
    # gitlab = "Your GitLab username"
    # linkedin = "Your LinkedIn username"
    # googleplus = "Your Google+ user id"
    facebook = "nosignal.tw"
    # reddit = "Your Reddit username"
    # hackernews = "Your Hacker News username"
    # stackoverflow = "Your Stackoverflow user id (number)"
    # keybase = "Your keybase.io username"
    # instagram = "Your Instagram username"
    # Disqus shortname
    # disqus = "Your disqus shortname"
    # Google Analytics API key.
    # ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    # mixpanel_api_key = "Your Mixpanel API key"
    author = "nosignal"
    # avatar = "/path/to/avatar"
    contact = "mailto:nosignal@nctu.edu.tw"
    # bio = "Your short bio"
    # Short subtitle/tagline. This is displayed in the header.
    # subtitle = "Short subtitle/tagline of your blog"
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
